---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    datacenter: primary
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager-0-2:9093
rule_files:
  - /opt/bitnami/prometheus/conf/rules.yaml
  - /opt/bitnami/prometheus/conf/alerts.yaml
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'graylog'
    static_configs:
            - targets: ['10.152.183.166:9833']

  - job_name: 'opensearch'
    static_configs:
            - targets: ['10.152.183.91:9200']
    metrics_path: '/_prometheus/metrics'
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['172.31.20.210:9100','172.31.48.127:9100','172.31.62.118:9100','172.31.51.187:9100']
    metric_relabel_configs:
      - source_labels: ['nodename']
        regex: '(qa.master)'
        target_label: nodename
        replacement: appz-${1}
      - source_labels: ['nodename']
        regex: 'qa.worker.node.(.*)'
        target_label: nodename
        replacement: appz-${1}
  - job_name: kube-state-metrics
    static_configs:
    - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
  - job_name: kubernetes-cadvisor
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels:
          - __meta_kubernetes_node_name
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
     module: [http_2xx] 
    static_configs:
    - targets:
       - https://sranjan1995-dev-graylog-5-2.1276c99e.lowtouch.cloud
       #- https://eu.apexaiq.com/api/v1/health/ping/
       #- https://az.apexaiq.com/api/v1/health/ping/
       #- https://docs.apexaiq.com/
       #- https://az-staging.apexaiq.com/api/v1/health/ping/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter-0-2:9115 
  - job_name: redis
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels:
          - __meta_kubernetes_namespace
        action: replace
        target_label: namespace
      - source_labels:
          - __meta_kubernetes_pod_name
        action: replace
        target_label: pod
      - source_labels:
          - pod
        regex: ((.*)redis(.*))
        action: keep
      - source_labels:
          - __address__
        target_label: __address__
        regex: ([^:]+)(:[6379]+)?
        replacement: ${1}
        action: drop
      - source_labels:
          - __address__
        regex: .*
        target_label: instance
        replacement: AppZ${1}
